### ISSUE TITLE
Variant Naming

### ISSUE THREAD

**Issue by SriMethan** [SriMethan/liantichess#99] opened 2022-08-08 16:30 UTC
Variants that are based on other variant and the only antichess rule they have is `mustCapture = true` or another antichess rule, but isn't based on antichess : These are **Coffee** variants.

Variants that are based on antichess completely and have a few rules implemented from another variant : These are **Anti** variants.

Variants which are not based on antichess should be **renamed**.

**Comment by TheYoBots** [comment] 2022-08-09 06:29
Duplicate of #72

**Closed** 2022-08-09 12:15 UTC
Labels: good first issue
